config/routes.rb
Rails.application.routes.draw do
  # User Login Routes
  get 'login', to: 'login#index'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'

  # User Registration Routes
  get 'registration', to: 'registration#index'
  post 'registration', to: 'registration#create'

  # User Profile Route
  get 'profile', to: 'profile#index'

  # Book Routes
  resources :books

  # Root Route
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  # Validation for Book Title
  validates :title, presence: true

  # Validation for Book Author
  validates :author, presence: true, length: { minimum: 2 }

  # Validation for Book Genre
  validates :genre, presence: true, length: { minimum: 2 }

  # Validation for Book Publication Year
  validates :publication_year, presence: true, length: { maximum: 4 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Validation for Name
  validates :name, presence: true, length: { minimum: 2 }

  # Validation for Username
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }

  # Validation for Email
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: '- Invalid Email!' }

  # Validation for Password
  has_secure_password
  validates :password, format: { with: /\A(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[[:^alnum:]])/x, message: '- Unsecure Password!' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Initialize Helper Methods
  helper_method :current_user, :authorized?

  ##
  # Current_User method
  # Check session storage has user information and get user information base on session data
  def current_user
    begin
      # Initialize current_user base on user login
      @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
    rescue => e
      # Logging errors when current user find
      logger.error("Current User Error: #{e.message}")
    end
  end

  ##
  # Authorized Method
  # Check user logged to the application
  def authorized?
    # Check user logged
    !!current_user
  end

  ##
  # Require_Auth Method
  # Check user Logged or not. If not redirect to Login View
  def require_auth
    # Checked logged and redirect
    redirect_to login_path, alert: 'Please Log In!' unless authorized?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # User Authentication Check
  before_action :require_auth

  # Set Book Values for operations
  before_action :set_book, only: %i[ show edit update destroy ]

  # Book Catalog View Load
  def index
    begin
      # Initialize books variable with All books from database
      @books = Book.all
    rescue => e
      # Logging errors when getting all books
      logger.error("Book Catalog Error: #{e.message}")
    end
  end

  # Book Create View Load
  def new
    # Initialize book object for creation
    @book = Book.new
  end

  # Book by Id View Load
  def show
  end

  # Book Update by Id View Load
  def edit
  end

  ##
  # Book Create Method
  # POST method for creating new book using book model params
  def create
    # Initialized book object with params data
    @book = Book.new(book_params)

    begin
      # Save book in database
      if @book.save
        # If book saved in database redirect to book view & notify book creation
        redirect_to book_url(@book), notice: "Book was successfully created."
      else
        # If book could not saved in database render same view and notify errors
        render :new, status: :unprocessable_entity
      end
    rescue => e
      # Logging errors when book creation
      logger.error("Book Creation Error: #{e.message}")
    end
  end

  ##
  # Book Update Method
  # PATCH method for update book using book model params
  def update
    begin
      # Update book in database
      if @book.update(book_params)
        # If book successfully updated redirect to book view & notify book update
        redirect_to book_url(@book), notice: "Book was successfully updated."
      else
        # If book could not updated in database render same view and notify errors
        render :edit, status: :unprocessable_entity
      end
    rescue => e
      # Logging errors when book update
      logger.error("Book Update Error: #{e.message}")
    end
  end

  ##
  # Book Remove Method
  # DELETE method for remove book from database using book id
  def destroy
    begin
      # Remove book in database
      if @book.destroy
        # Redirect to Catalog View & notify book removal
        redirect_to books_url, notice: "Book was successfully removed."
      else
        # If book could not removed in database render same view and notify errors
        render :show, status: :unprocessable_entity
      end
    rescue => e
      # Logging errors when book remove
      logger.error("Book Remove Error: #{e.message}")
    end
  end

  private

  ##
  # Book Params Method
  # Set params for securely process the books
  def book_params
    params.require(:book).permit(:title, :author, :genre, :publication_year)
  end

  ##
  # Set Book Method
  # Initialized book object finding book using params id
  def set_book
    begin
      @book = Book.find(params[:id])
    rescue => e
      # Logging errors when book find
      logger.error("Book Find Error: #{e.message}")
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  # User Login Page Load
  def index
  end

  ##
  # User Login Method
  # POST method for user login with username & password
  def create
    begin
      # Find user by username in database
      user = User.find_by(username: params[:username])

      # If user found in database check whether user authenticate with correct password
      if user.present? && user.authenticate(params[:password])
        # If username and password are correct store user information in session storage
        session[:user_id] = user.id

        # Redirect to Root Page
        redirect_to root_path, notice: 'User Login Successfully!'
      else
        # When Username and Password incorrect Notify Error & render Login view
        flash[:notice] = 'Username or Password Incorrect!'
        render :index, status: :unprocessable_entity
      end
    rescue => e
      # Logging errors when user login
      logger.error("User Login Error: #{e.message}")
    end
  end

  ##
  # User Logout Method
  # DELETE method for user logout
  def destroy
    begin
      if session[:user_id].present?
        # Remove session storage user information
        session[:user_id] = nil

        # Redirect to Root Path
        redirect_to root_path, notice: 'User Logout Successfully!'
      end
    rescue => e
      # Logging errors when user login
      logger.error("User Logout Error: #{e.message}")
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  # User Authentication Check
  before_action :require_auth

  # User Profile View Load
  def index
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  # User Registration Page Load
  def index
    @user = User.new
  end

  ##
  # User Registration Method
  # POST method for user registration using user model params
  def create
    # Initialized user object with params data
    @user = User.new(user_params)

    begin
      # Saving user in DB
      if @user.save
        # Save user id in session storage if user saved in database
        session[:user_id] = @user.id

        # Redirect to Root Path and Notify user registration
        redirect_to root_path, notice: 'User Successfully Registered!'
      else
        # If User didn't registered load same page and notify errors
        render :index, status: :unprocessable_entity
      end
    rescue => e
      # Logging errors when user registration
      logger.error("User Registration Error: #{e.message}")
    end
  end

  private

  ##
  # User Params Method
  # User parameters for create new user
  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/books/_book.html.erb
<!-- Card -->
<div class="card mb-3" id="<%= dom_id book %>">
  <div class="row g-0">
    <!-- Card Header Section -->
    <div class="col-md-4">
      <img src="https://img.freepik.com/free-vector/hand-drawn-flat-design-stack-books_23-2149342941.jpg" class="img-fluid rounded-start" alt="Book">
    </div>

    <!-- Card Body Section -->
    <div class="col-md-8">
      <div class="card-body">

        <!-- Book Title -->
        <h5 class="card-title"><%= book.title %></h5>

        <!-- Book Author-->
        <p class="card-text"><strong>Author:</strong> <%= book.author %></p>

        <p class="card-text">
          <small class="text-body-secondary">
            <!-- Book Genre -->
            <strong>Genre:</strong> <%= book.genre %>
            <br/>
            <!-- Book Publication Year -->
            <strong>Publication year:</strong> <%= book.publication_year %>
          </small>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<!-- Card view Body -->
<div class="card-body">
  <%= form_with(model: book) do |form| %>

    <!-- Form Validation Errors View -->
    <% if book.errors.any? %>
      <div style="color: red">

        <!-- Errors count view -->
        <h5><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h5>

        <ul>
          <!-- Errors List view-->
          <% book.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Input field book title -->
    <div class="mb-3 form-group">
      <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
    </div>

    <!-- Input field book author -->
    <div class="mb-3 form-group">
      <%= form.text_field :author, class: "form-control", placeholder: "Author" %>
    </div>

    <!-- Input field book genre -->
    <div class="mb-3 form-group">
      <%= form.text_field :genre, class: "form-control", placeholder: "Genre" %>
    </div>

    <!-- Input field book publication year -->
    <div class="mb-3 form-group">
      <%= form.number_field :publication_year, class: "form-control", placeholder: "Publication Year" %>
    </div>

    <!-- Submit button -->
    <div class="mb-3 form-group">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="card">
  <!-- Card view header -->
  <div class="card-header">
    <h2>Update Book</h2>
  </div>

  <!-- Render Book Creation/Update Form View -->
  <%= render "form", book: @book %>
</div>
<br/>

<!-- Buttons Group -->
<div class="btn-group" role="group" aria-label="Basic example">
  <!-- Buttons for show book information -->
  <%= link_to "Show this book", @book, class: "btn btn-success" %>

  <!-- Buttons for books catalog -->
  <%= link_to "Books Catalog", books_path, class: "btn btn-primary" %>
</div>

app/views/books/index.html.erb
<h1>Books Catalog</h1>

<div id="books" class="my-3">
  <div class="row">

    <!-- Generate Books List -->
    <% @books.each do |book| %>
      <div class="col-sm-6 col-md-4 col-lg-3">

        <!-- Card View -->
        <div class="card mb-3" id="<%= dom_id book %>">

          <!-- Book Image -->
          <img src="https://img.freepik.com/free-vector/hand-drawn-flat-design-stack-books_23-2149342941.jpg" class="card-img-top" alt="book">

          <!-- Card Body Section -->
          <div class="card-body">

            <!-- Book Title -->
            <h5 class="card-title"><%= book.title %></h5>

            <!-- Book Author -->
            <p class="card-text"><%= book.author %></p>

            <!-- Single Book View Button-->
            <%= link_to "Show this book", book, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br/>

app/views/books/new.html.erb
<div class="card">
  <!-- Card view header -->
  <div class="card-header">
    <h2>Create Book</h2>
  </div>

  <!-- Render Book Creation/Update Form View -->
  <%= render "form", book: @book %>
</div>
<br/>

<!-- Button for Book Catalog -->
<div>
  <%= link_to "Books Catalog", books_path, class: "btn btn-success" %>
</div>

app/views/books/show.html.erb
<!-- Render Book View -->
<%= render @book %>

<!-- Buttons Group -->
<div class="btn-group" role="group" aria-label="Basic example">
  <!-- Buttons for update book information -->
  <%= link_to "Update this book", edit_book_path(@book), class: "btn btn-success" %>

  <!-- Buttons for books catalog -->
  <%= link_to "Books Catalog", books_path, class: "btn btn-primary" %>

  <!-- Buttons for remove book -->
  <%= button_to "Remove this book", @book, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure want to remove the book?" }, method: :delete, class: "btn btn-danger" %>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  <!-- Alert Message -->
  <%= alert %>

  <!-- Alert Close Button -->
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <!-- Root Path -->
    <%= link_to "Book CMS", root_path, class: "navbar-brand" %>

    <!-- Collapse Button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- NavBar Paths -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left Side Paths -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- Books List Path -->
        <li class="nav-item">
          <%= link_to "Catalog", books_path, class: "nav-link" %>
        </li>

        <!-- Book Create Path -->
        <li class="nav-item">
          <%= link_to "New Book", new_book_path, class: "nav-link" %>
        </li>
      </ul>

      <!-- Right Side Paths -->
      <ul class="navbar-nav d-flex">
        <!-- Check user logged or not -->
        <% if authorized? %>
          <!-- Current User -->
          <li class="nav-item">
            <a class="nav-link disabled" href=""><%= current_user.username %></a>
          </li>

          <!-- Profile Path -->
          <li class="nav-item">
            <%= link_to "Profile", profile_path, class: "nav-link" %>
          </li>

          <!-- Sign Out Path -->
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %><!-- If user not logged -->
          <!-- Sign In Path -->
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>

          <!-- Sign Up Path -->
          <li class="nav-item">
            <%= link_to "Sign Up", registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  <!-- Notice Message -->
  <%= notice %>

  <!-- Notice Close Button -->
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>BookCMS</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<!-- Header Section (Navigation Bar) -->
<%= render 'layouts/header' %>
<br/>
<!-- Body Section -->
<div class="container">
  <h1>Book Catalog Management System</h1>
  <br/>
  <!-- Notice Messages -->
  <% if notice %>
    <%= render 'layouts/notice' %>
  <% end %>

  <!-- Alert Messages -->
  <% if alert %>
    <%= render 'layouts/alert' %>
  <% end %>

  <!-- Main Body Rendering -->
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

app/views/login/index.html.erb
<div class="card auth-card">
  <!-- Log in card view header -->
  <div class="card-header">
    <h2>Log in</h2>
  </div>

  <!-- Log in card view Body -->
  <div class="card-body">
    <%= form_with url: login_path do |f| %>

      <!-- Input Field Username -->
      <div class="mb-3 form-group">
        <%= f.text_field :username, class: "form-control", placeholder: "Username", required: true %>
      </div>

      <!-- Input Field Password -->
      <div class="mb-3 form-group">
        <%= f.password_field :password, class: "form-control", placeholder: "Password", required: true %>
      </div>

      <!-- Submit Button -->
      <div class="mb-3 actions">
        <%= f.submit "Log in", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>